-- CreateTable
CREATE TABLE "Sibling" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "avatarUrl" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Turn" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "siblingId" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'CURRENT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Turn_siblingId_fkey" FOREIGN KEY ("siblingId") REFERENCES "Sibling" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Walk" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "siblingId" INTEGER NOT NULL,
    "timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "photoPath" TEXT NOT NULL,
    "verificationStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "confidenceScore" REAL,
    CONSTRAINT "Walk_siblingId_fkey" FOREIGN KEY ("siblingId") REFERENCES "Sibling" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
